# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with: 
          java-version: '8'
          distribution: 'adopt'
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@5188e412814bdb5c63ee55c548f2448044a673de
        uses: subosito/flutter-action@v1.5.1
        with:
          flutter-version: "1.22.5"
          channel: stable
      - run: ls
      - run: cd myApp
      - run: ls
      - run: flutter pub get
      - run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}
